### ISSUE TITLE
Transaction too long

### ISSUE THREAD

**Issue by KhmerRun** [schmeckles22/SolaceCoin#29]
Hello,

I tested to mine some SolaceCoin at https://pool.solace-coin.com/ and the payment sent out from from them as listed in transaction list but waiting for hours already and still not see in my wallet.

Is it normal that too long for a couple of hours?

v0.2.0.0-2a4f321 already sync with blockchain.

**Comment by Ingerulro** [comment]
Can you give us more info? Like transaction ID.

**Comment by KhmerRun** [comment]
Hi, I just checked the pool again now an seen they changed the pool software and I could not snapshot the list.

I copied some in my browser history:
http://explorer.solace-coin.com/tx/ff377c728f8eb5a9fdc2a6319e17af9af7f37e5cf069dbf3ea751404a4f29e48

http://explorer.solace-coin.com/tx/44b27700c129e53a34d2d6466e581d2fc561c49f44862a8d483178cf1c29f589

http://explorer.solace-coin.com/tx/3b9ba56abf943e4ac326b48103d8bfbd278fbc803b5ba8df3d5f1c8173bbd58a

I just also sync the daemon data again and wallet is still zero.

**Comment by KhmerRun** [comment]
This was fixed with re-generate from seed.
