### ISSUE TITLE
Can't start daemon

### ISSUE THREAD

**Issue by KhmerRun** [schmeckles22/SolaceCoin#34]
Hello,

I just compiled SolaceCoin from git just now and try to started daemon from empty data dir via:

user@localhost:~/daemon-solace/bin$ ./solaced --data-dir=./data
Creating the logger system
2018-Apr-21 22:19:24.731308 Initializing cryptonote protocol...
2018-Apr-21 22:19:24.731347 Cryptonote protocol initialized OK
2018-Apr-21 22:19:24.731557 Initializing p2p server...
2018-Apr-21 22:19:24.922381 Set limit-up to 2048 kB/s
2018-Apr-21 22:19:24.922445 Set limit-down to 8192 kB/s
2018-Apr-21 22:19:24.922471 Set limit-up to 2048 kB/s
2018-Apr-21 22:19:24.922510 Set limit-down to 8192 kB/s
2018-Apr-21 22:19:24.922576 Binding on 0.0.0.0:19798
2018-Apr-21 22:19:24.922649 Net service bound to 0.0.0.0:19798
2018-Apr-21 22:19:24.922663 Attempting to add IGD port mapping.
2018-Apr-21 22:19:28.926932 No IGD was found.
2018-Apr-21 22:19:28.926995 P2p server initialized OK
2018-Apr-21 22:19:28.927115 Initializing core rpc server...
2018-Apr-21 22:19:28.927185 Binding on 127.0.0.1:19799
2018-Apr-21 22:19:28.927261 Core rpc server initialized OK on port: 19799
2018-Apr-21 22:19:28.927292 Initializing core...
2018-Apr-21 22:19:28.927475 Loading blockchain from folder ./data/lmdb ...
2018-Apr-21 22:19:28.927538 option: fast
2018-Apr-21 22:19:28.927562 option: async
2018-Apr-21 22:19:28.927582 option: 1000
2018-Apr-21 22:19:28.927985 Error attempting to retrieve a hard fork version at height 0 from the db: MDB_NOTFOUND: No matching key/data pair found
Aborted

**Comment by schmeckles22** [comment]
Hello,

Have you compiled manually or used pre-compiled release?

**Comment by Ingerulro** [comment]
It is a known issue when compiling without "release-static" argument. Please recompile but using: `make release-static`

**Comment by KhmerRun** [comment]
There is no issue if I use existing data dir synchronizing before.
